### ISSUE TITLE
Linked extension not working

### ISSUE THREAD

**Issue by Syntle** [amoAR/AWA-Key-Checker#1]
The readme file includes a link to `Tampermonkey` which takes you to an extension called `User JavaScript and CSS` which doesn't work with the UserScript.

**Comment by amoAR** [comment]
Do you mean this extension will appear?
https://chromewebstore.google.com/detail/user-javascript-and-css/nbhcbdghjpllgmfilhnhkllmkecfmpld

**Comment by Syntle** [comment]
Yes and it doesn't work with the UserScript, instead it spits the following error in console.


![image](https://github.com/amoAR/AWA-Key-Checker/assets/43820255/d58f1476-4d44-4a91-b98e-04dd94579058)

**Comment by amoAR** [comment]
1. **Remove or disable** all rules for AlienwareArena pages that set in _**User JavaScript and CSS**_ extension
2. Make sure your installed **_UserscriptManager(like Tampermonkey)_** is **enabled** and has **access** to Github and AWA sites
3. Try the install link or install the script manually in your installed UserscriptManager by the following URL: 

> https://github.com/amoAR/AWA-Key-Checker/raw/main/AWACheck.user.js

**Comment by T4bletopG4mes** [comment]
I had the same problem, User JavaScript and CSS (ex tampermonkey?) doesnt know how to read the UserScript part like ViolentMonkey or Greasemonkey does to have the extra required lib. My suggestion would be to remove the link to tampermonkey since the other two are much more plug and play.

**Comment by amoAR** [comment]
It seems that this case is an exception that causes conflict between extensions. You can bypass this problem by temporarily disabling **_User JavaScript and CSS_** and manually installing **AWA Key Checker** from [URL](https://github.com/amoAR/AWA-Key-Checker/raw/main/AWACheck.user.js).
